//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeBranchTaskManager.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrangeBranchTaskManager.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar tarefa..
        /// </summary>
        public static string ERROR_BAD_REQUEST_TASK {
            get {
                return ResourceManager.GetString("ERROR_BAD_REQUEST_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar tarefas..
        /// </summary>
        public static string ERROR_BAD_REQUEST_TASKS {
            get {
                return ResourceManager.GetString("ERROR_BAD_REQUEST_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar tarefa..
        /// </summary>
        public static string ERROR_CREATE_TASK {
            get {
                return ResourceManager.GetString("ERROR_CREATE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar o usuário..
        /// </summary>
        public static string ERROR_CREATE_USER {
            get {
                return ResourceManager.GetString("ERROR_CREATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao excluir a tarefa..
        /// </summary>
        public static string ERROR_DELETE_TASK {
            get {
                return ResourceManager.GetString("ERROR_DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário com o email informado..
        /// </summary>
        public static string ERROR_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ERROR_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave secreta inválida..
        /// </summary>
        public static string ERROR_INVALID_SECRET_KEY {
            get {
                return ResourceManager.GetString("ERROR_INVALID_SECRET_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa não encontrada..
        /// </summary>
        public static string ERROR_NOT_FOUND_TASK {
            get {
                return ResourceManager.GetString("ERROR_NOT_FOUND_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma tarefa encontrada..
        /// </summary>
        public static string ERROR_NOT_FOUND_TASKS {
            get {
                return ResourceManager.GetString("ERROR_NOT_FOUND_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar tarefa no banco de dados..
        /// </summary>
        public static string ERROR_SAVE_TASK_DB {
            get {
                return ResourceManager.GetString("ERROR_SAVE_TASK_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar a tarefa..
        /// </summary>
        public static string ERROR_UPDATE_TASK {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_TASK", resourceCulture);
            }
        }
    }
}
