//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeBranchTaskManager.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrangeBranchTaskManager.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar tarefa..
        /// </summary>
        public static string ERROR_BAD_REQUEST_TASK {
            get {
                return ResourceManager.GetString("ERROR_BAD_REQUEST_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar tarefas..
        /// </summary>
        public static string ERROR_BAD_REQUEST_TASKS {
            get {
                return ResourceManager.GetString("ERROR_BAD_REQUEST_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar tarefa..
        /// </summary>
        public static string ERROR_CREATE_TASK {
            get {
                return ResourceManager.GetString("ERROR_CREATE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar o usuário..
        /// </summary>
        public static string ERROR_CREATE_USER {
            get {
                return ResourceManager.GetString("ERROR_CREATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao excluir a tarefa..
        /// </summary>
        public static string ERROR_DELETE_TASK {
            get {
                return ResourceManager.GetString("ERROR_DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição não pode ser vazia..
        /// </summary>
        public static string ERROR_DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_DESCRIPTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição deve ter no máximo 300 caracteres..
        /// </summary>
        public static string ERROR_DESCRIPTION_TOO_LONG {
            get {
                return ResourceManager.GetString("ERROR_DESCRIPTION_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data não pode estar vazia..
        /// </summary>
        public static string ERROR_DUE_DATE_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_DUE_DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data não pode ser no passado..
        /// </summary>
        public static string ERROR_DUE_DATE_PAST {
            get {
                return ResourceManager.GetString("ERROR_DUE_DATE_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário com o email informado..
        /// </summary>
        public static string ERROR_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ERROR_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereço de email não pode estar vazio..
        /// </summary>
        public static string ERROR_EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email não pode exceder 100 caracteres..
        /// </summary>
        public static string ERROR_EMAIL_TOO_LONG {
            get {
                return ResourceManager.GetString("ERROR_EMAIL_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id não pode ser vazio..
        /// </summary>
        public static string ERROR_EMPTY_ID {
            get {
                return ResourceManager.GetString("ERROR_EMPTY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id informado não corresponde ao registro em questão..
        /// </summary>
        public static string ERROR_ID_DOESNT_MATCH {
            get {
                return ResourceManager.GetString("ERROR_ID_DOESNT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereço de email é inválido..
        /// </summary>
        public static string ERROR_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("ERROR_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id invalido..
        /// </summary>
        public static string ERROR_INVALID_ID {
            get {
                return ResourceManager.GetString("ERROR_INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida..
        /// </summary>
        public static string ERROR_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave secreta inválida..
        /// </summary>
        public static string ERROR_INVALID_SECRET_KEY {
            get {
                return ResourceManager.GetString("ERROR_INVALID_SECRET_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa não encontrada..
        /// </summary>
        public static string ERROR_NOT_FOUND_TASK {
            get {
                return ResourceManager.GetString("ERROR_NOT_FOUND_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma tarefa encontrada..
        /// </summary>
        public static string ERROR_NOT_FOUND_TASKS {
            get {
                return ResourceManager.GetString("ERROR_NOT_FOUND_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string ERROR_NOT_FOUND_USER {
            get {
                return ResourceManager.GetString("ERROR_NOT_FOUND_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode estar vazia..
        /// </summary>
        public static string ERROR_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode exceder 100 caracteres..
        /// </summary>
        public static string ERROR_PASSWORD_TOO_LONG {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar tarefa no banco de dados..
        /// </summary>
        public static string ERROR_SAVE_TASK_DB {
            get {
                return ResourceManager.GetString("ERROR_SAVE_TASK_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título não pode ser vazio..
        /// </summary>
        public static string ERROR_TITLE_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_TITLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título deve ter no máximo 100 caracteres..
        /// </summary>
        public static string ERROR_TITLE_TOO_LONG {
            get {
                return ResourceManager.GetString("ERROR_TITLE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar a tarefa..
        /// </summary>
        public static string ERROR_UPDATE_TASK {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode estar vazio..
        /// </summary>
        public static string ERROR_USERNAME_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_USERNAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode exceder 100 caracteres..
        /// </summary>
        public static string ERROR_USERNAME_TOO_LONG {
            get {
                return ResourceManager.GetString("ERROR_USERNAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
